### ISSUE TITLE
Add testing for the main page using Playwright

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#109]
**Task Description:** Add end-to-end tests using Playwright (new framework) for the main page.

**Suggested Workflow:**
- [ ] Create a new branch that is an offshoot of `dev` called `testing-main-page`
- [ ] Add tests to `main_page.spec.js` in the  `tests/e2e/main_page` directory
- [ ] Once you're done, create a pull request back to `dev`
- [ ] Resolve all merge conflicts and merge to `dev`

See [this](https://playwright.dev/docs/intro) to get started.

**Comment by gilkeidar** [comment]
Once pushing to `main`, fix URL to be of the deployed GitHub page so that the automatically generated CI/CD workflow of E2E tests can run correctly!

**Comment by gilkeidar** [comment]
Duplicate of #113
