### ISSUE TITLE
Add tests for the main page using Playwright

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#113]
**Task Description:** Add a few end-to-end tests to verify functionality of the main page.

**Suggested Workflow:**
- [x] Create a new branch that is an offshoot of `dev` called `test-main-page`
- [x] Create a folder in the `tests/e2e/` directory called `main_page`
- [x] Add the file `main_page.spec.js`
- [x] Write a few tests (you can generate user actions / find locators via using the [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright)
- [x] Check that they work (they don't necessarily have to pass - they might catch a few bugs!)
- [x] When you're done, make a pull request back into `dev`
- [x] Resolve all merge conflicts and merge the pull request into `dev`
