### ISSUE TITLE
Add tests for the Molybdomancy Mini-app using Playwright

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#115]
**Task Description:** Add a few end-to-end tests to verify functionality of the Molybdomancy mini-app;

**Suggested Workflow:**
- [x] Create a new branch that is an offshoot of `dev` called `test-molybdomancy`
- [x] Create a folder in the `tests/e2e/` directory called `molybdomancy`
- [x] Add the file `molybdomancy.spec.js`
- [x] Write a few tests (you can generate user actions / find locators via using the [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright)
- [x] Check that they work (they don't necessarily have to pass - they might catch a few bugs!)
- [x] When you're done, make a pull request back into `dev`
- [x] Resolve all merge conflicts and merge the pull request into `dev`
