### ISSUE TITLE
Add tests for the Yin Yang Coin Mini-app using Playwright

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#118]
**Task Description:** Add a few end-to-end tests to verify functionality of the Yin Yang Coin mini-app;

**Suggested Workflow:**
- [x] Create a new branch that is an offshoot of `dev` called `test-yin-yang-coin`
- [x] Create a folder in the `tests/e2e/` directory called `yin-yang-coin`
- [ ] Add the file `yin-yang-coin.spec.js`
- [ ] Write a few tests (you can generate user actions / find locators via using the [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright)
- [ ] Check that they work (they don't necessarily have to pass - they might catch a few bugs!)
- [ ] When you're done, make a pull request back into `dev`
- [ ] Resolve all merge conflicts and merge the pull request into `dev`

**Comment by Samanzzz** [comment]
closed
