### ISSUE TITLE
Add Documentation to Yin Yang Coin Code

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#80]
**Task Description:** Add comments to HTML, CSS, and JS files.

**Recommended Approach:**

- [x] Make a new branch that is an offshoot of `dev` called `add-documentation-yin-yang-coin`.
- [ ] Add all your documentation to Yin Yang Coin's HTML, CSS, and JS files in this branch
- [ ] Once you're done, make a pull request back to `dev`
- [ ] Resolve any merge conflicts and merge the pull request into `dev`.

**Tips:**

For HTML files:
- use comments to explain the structure of the mini-app, as well as the purpose of components

For CSS files:
- use comments to separate the code into sections (e.g. group CSS by related components and use comments to specify these categories)
- purpose: make the CSS as readable as possible (e.g., explain the purpose of using particular properties)

For JS files:
- use JSDocs comments above variables, functions, event listeners, and classes (these  are used to generate docs)
    - when using JSDocs, try to use appropriate tags (see https://jsdoc.app/ for reference)
    - You can also check out `engine.js` to see some examples of tag use
- use normal comments to explain processes in the code (e.g. like normal comments)

**For all 3:** If you found a good resource online that explains something, it's a good idea to include the link in a comment!
