### ISSUE TITLE
Add Test Cases to Fortune Stick mini-app

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#82]
**Task Description:** Add Jest unit tests to the Fortune Stick mini-app.

- [x] In the `tests` directory, create the subdirectory `fortune-stick`.
- [ ] Add at least one file (e.g. `fortune-stick.test.js`)
- [ ] Write unit tests to check the functionality of your code

**Note:** You **cannot** call `fetch()` in Jest unit tests. This includes testing whether a JSON file was read correctly by the `FortuneEngine`.

If you want to test a feature that relies on the `FortuneEngine`, do the following:

```javascript
  //  Create a FortuneEngine object
  const engine = new FortuneEngine('Test');

  //  Can't test fetch() in Jest - assume read.
  engine.initialized = true;

  //  Set JSON contents
  const jsonContents = {
      // insert your JSON file's contents here
  };

  engine.json_contents = jsonContents;

  const outcomes = engine.json_contents['option-result pair'];

  engine.outcomes = outcomes;

  // can safely call get_random_subset() now
```

Is it gross? Yes. But Jest is made for unit testing - I believe we need end-to-end testing support to facilitate testing of this kind.
