### ISSUE TITLE
Add Test Cases to Yin Yang Code mini-app

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#84]
**Task Description:** Add Jest unit tests to the Yin Yang Coin mini-app.

- [ ] In the `tests` directory, create the subdirectory `yin-yang-coin`.
- [ ] Add at least one file (e.g. `yin-yang-coin.test.js`)
- [ ] Write unit tests to check the functionality of your code

**Note:** You **cannot** call `fetch()` in Jest unit tests. This includes testing whether a JSON file was read correctly by the `FortuneEngine`.

If you want to test a feature that relies on the `FortuneEngine`, do the following:

```javascript
  //  Create a FortuneEngine object
  const engine = new FortuneEngine('Test');

  //  Can't test fetch() in Jest - assume read.
  engine.initialized = true;

  //  Set JSON contents
  const jsonContents = {
      // insert your JSON file's contents here
  };

  engine.json_contents = jsonContents;

  const outcomes = engine.json_contents['option-result pair'];

  engine.outcomes = outcomes;

  // can safely call get_random_subset() now
```

Is it gross? Yes. But Jest is made for unit testing - I believe we need end-to-end testing support to facilitate testing of this kind.

**Comment by gilkeidar** [comment]
Closing this issue; unfortunately we no longer have time to meaningfully test - writing tests now would be performative but not helpful as we don't have time to address issues that come up.

**Comment by gilkeidar** [comment]
Closing this issue; unfortunately we no longer have time to meaningfully test - writing tests now would be performative but not helpful as we don't have time to address issues that come up.

**Comment by gilkeidar** [comment]
Closing this issue; unfortunately we no longer have time to meaningfully test - writing tests now would be performative but not helpful as we don't have time to address issues that come up.

**Comment by gilkeidar** [comment]
Closing this issue; unfortunately we no longer have time to meaningfully test - writing tests now would be performative but not helpful as we don't have time to address issues that come up.

**Comment by gilkeidar** [comment]
Closing this issue; unfortunately we no longer have time to meaningfully test - writing tests now would be performative but not helpful as we don't have time to address issues that come up.

**Comment by gilkeidar** [comment]
Closing this issue; unfortunately we no longer have time to meaningfully test - writing tests now would be performative but not helpful as we don't have time to address issues that come up.
