### ISSUE TITLE
Remove Magic Numbers from Yin Yang Coin Code

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#98]
**Task Description:** Remove magic numbers from the Yin Yang Coin mini-app's code.

**Recommended Approach:**

- [ ] Make a new branch that is an offshoot of `dev` called `remove-magic-numbers-yin-yang-coin`.
- [ ] Do all of your work in this branch (find and replace magic numbers with appropriate constants, which should be documented using JSDocs)
- [ ] Once you're done, make a pull request back to `dev`
- [ ] Resolve any merge conflicts and merge the pull request into `dev`.
